name: release
on:
  push:
    tags:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      # Example: 1.0.0
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle assembleDist
        run: ./gradlew -PappVersion=${{github.ref_name}} assembleDist --scan

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: ./playground/build/distributions/**
