on:
  push:
    branches:
    - main
    - release
  pull_request:
    branches:
    - main
    - release

jobs:
  ci:
    name: Check and build
    permissions:
      pull-requests: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
        gradle-home-cache-cleanup: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build --scan

    - name: Execute Gradle check
      run: ./gradlew check --scan

    - name: Add Scan URL as PR comment
      uses: actions/github-script@v5
      if: github.event_name == 'pull_request' && failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
          })
